name: Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: which chromium-browser
    - run: export CHROME_BIN=/usr/bin/chromium-browser
    - run: npm i -g karma
    - run: npm i
    - run: npm run test:all
